### ISSUE TITLE
CommonsExecWebServerFactoryBean creation with environment

### ISSUE THREAD

**Issue by rwinch** [spring-projects-experimental/spring-boot-testjars#19]
It might be interesting to be able to create test jars through Spring Properties. Something like the following could leverage gh-10 to create an Authorization Server:

```yml
spring:
  testjars:
    authorization-server:
      resources: maven:org.springframework.boot:spring-boot-authorization-server
```

Using gh-13 we could then configure a password using something like to set any custom properties for that authorization server:

src/test/resources/testjars/application-authorization-server.properties
```properties
spring.security.user.password=password 
```
